# Generated by Django 6.1 on 2026-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('competition', 'Competition')], default='full-time', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
