# Generated by Django 5.2.17 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_id_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
