# Generated by Django 6.1 on 2026-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_id_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='capabilities',
            field=models.TextField(blank=True, help_text='Satu poin per baris, contoh:\nBasic Python\nBasic Pandas'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Contoh: devicon-python-plain (lihat devicon.dev)', max_length=100),
        ),
    ]
