# Generated by Django 6.1 on 2026-09-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill_capabilities_skill_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Link gambar sendiri (opsional). Kalau diisi, ini dipakai duluan, mengalahkan icon_class.'),
        ),
    ]
